basePath: /v1
definitions:
  models.BasicResponse:
    properties:
      message: {}
      status_code:
        type: integer
    type: object
  models.Pagination:
    properties:
      page:
        type: integer
      page_size:
        type: integer
      total:
        type: integer
      total_page:
        type: integer
    type: object
  models.ResponseWithPaginate:
    properties:
      data: {}
      message: {}
      pagination:
        $ref: '#/definitions/models.Pagination'
      status_code:
        type: integer
    type: object
host: localhost:3008
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is api for monitoring service.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Echo Swagger Monitoring API
  version: "1.0"
paths:
  /monitor/visitor/count:
    get:
      consumes:
      - application/json
      description: Get count visitor
      operationId: count-visitor
      parameters:
      - description: flag in zone cashier
        in: query
        name: is_cashier
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseWithPaginate'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.BasicResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.BasicResponse'
      summary: Get count visitor
      tags:
      - Monitoring Visitor
schemes:
- http
swagger: "2.0"
